name: Test CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.6
      - name: Install requirements
        run: |
          cd web
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary
      - name: Run Tests
        env:
          SECRET_KEY: postgres
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASS: postgres
          DB_SERVICE: postgres
          DB_PORT: 5432
        run: |
          cd web
          python manage.py test

    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
